import re

print(re.sub('[ab]','*','abcda abcghiabc hmnoadc'))
print(re.sub('ab','*','abcda abcghiabc hmnoadc'))
print(re.sub('[ab][123]','*','a1b2cda3 a2b2cg4hi1abc hmnoadc'))
print(re.sub('a.c','*','abcda abcghiabc hmnoadc'))
print(re.sub('a..g','*','abcda abcghiabc hmnoadc'))
print(re.sub('ab+','*','abbbbbbbcda abcghiabc hmnoadc'))
print(re.sub(r'ab{3,6}','*','abbbbbcda abbcghiabc hmnoadc'))
print(re.sub('^abc','*','abcda abcghiabc hmnoadc'))
print(re.sub('abc','*','abcda abcghiabc hmnoadc'))
print(re.sub('abc$','*','abcda abcghiabc hmnoadc'))
print(re.sub(r'\d','*','This is the test. Or is it?'))
print(re.sub(r'\D','*','This is the test. Or is it?'))
print(re.sub(r'\w','*','This is the test. Or is it?'))
print(re.sub(r'\W','*','This is the test. Or is it?'))
print(re.sub(r'\s','*','This is the test. Or is it?'))
print(re.sub(r'\S','*','This is the test. Or is it?'))
print(re.sub(r'the(?=cat)','*','the dog and the cat'))
print(re.sub(r'(?<=)the','*','Athens is the capital'))
print(re.sub(r'(?<!\w)[Tt]he(?!\w)','*','The cat is on the lathe there.'))
print(re.sub('(?!)ab','*','ab AB'))